name: Deploy to Github Pages

on: push

jobs:
  deploy:
    name: Deploying to Github Pages

    runs-on: ubuntu-latest

    steps:
      - name: Deploy React Application to Github Pages
        uses: joshuanoronha/react-deploy-github-pages@1.0.01
